version: '3.8'

services:
  db:
    image: postgres:13 # Ou a versão mais recente do PostgreSQL
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 50912
      POSTGRES_DB: barber
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
